# Generated by Django 5.1.5 on 2025-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_add_event_model_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_event_model',
            name='image',
            field=models.ImageField(default='default_event.jpg', upload_to='event_images/'),
        ),
    ]
