# Generated by Django 5.1.5 on 2025-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rsvp_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_event_model',
            name='image',
            field=models.ImageField(default='https://i.pinimg.com/736x/ed/f0/1b/edf01be817dca367651fc74e43a3f2be.jpg', max_length=5200, upload_to='event_images/'),
        ),
    ]
